# Deploy client on every pull request
name: Deploy client to zeit (DEV)

on:
  push:
    branches:
      - 'no-branch'

# on:
#   push:
#     branches-ignore:
#       - 'develop'

jobs:
  setup:
    name: Setup deployment environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1 # Used to install node environment
        with:
          node-version: '10.x' # Use the same node.js version as the one Zeit's uses (currently node10.x)

  deploy-to-dev:
    name: Deploy client to zeit (DEV)
    runs-on: ubuntu-latest
    needs: setup # Need to wait for setup
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}
