name: Lint client and check format

on:
  push:
    branches-ignore:
      - 'develop'

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1 # Used to install node environment
        with:
          node-version: '10.x'

  lint-client:
    name: Lint client and check format
    runs-on: ubuntu-latest
    needs: setup # Need to wait for setup
    steps:
      - uses: actions/checkout@v1 # Get last commit pushed

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Lint client
        run: yarn lint:check

      - name: Check format
        run: yarn format:check

      # - name: Build client
      #   run: yarn build
