name: Unit test

on:
  push:
    branches-ignore:
      - 'develop'

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1 # Used to install node environment
        with:
          node-version: '10.x'

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: setup # Need to wait for setup
    steps:
      - uses: actions/checkout@v1 # Get last commit pushed

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:unit

      # - name: Jest Annotations & Coverage
      #   uses: mattallty/jest-github-action@v1.0.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      #   with:
      #     # Runs tests related to the changes since the base branch of your pull request
      #     # Default to false if not set
      #     changes-only: true

      - name: Codecov upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.REPO_TOKEN }} # not required for public repos
          file: ./coverage/clover.xml # optional
          fail_ci_if_error: false
